### ISSUE TITLE
returns: undefined

### ISSUE THREAD

**Issue by battosai50** [pcurt/MMM-BlaguesAPI#1]
Hello,

I tried to add your module.
I cloned in the modules folder, created an account in blagues-api.fr, generated the token and added in the config.js:
    {
      module: 'MMM-BlaguesAPI',
      position: 'bottom_bar',
      type: {
        type: 'global',
        fetchInterval: 60000,
        blaguesApiToken: 'my_generated_token'
      }
    },

I tried to replace "type:{" by "config:{", in co,nformity to other modules, thinking that you may have made a mistake in your exemple but it didn't work (nothing is written, undefined disappeared).

I'm using the new MMM-GoogleAssistant v6.0.0

Any idea on how to make it work?

Thank you in advance

**Comment by pcurt** [comment]
You have to add this pattern to your config file
```
module: 'MMM-BlaguesAPI',
position: "bottom_bar",
config: {
    type: "global",
    fetchInterval: 60000,
    blaguesApiToken: ""
}
```
The type is the joke category. The API allows the following categories
`GET /api/type/:type:/random // type: global, dev, dark, limit, beauf, blondes`
I have pushed a fix to use the categories.

Can you please update your module and test again ?

**Comment by battosai50** [comment]
Hello,

With the update, it works perfectly.
Thank you.

**Comment by battosai50** [comment]
Closed
