### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [pcurt/MMM-BlaguesAPI#2]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md

**Comment by pcurt** [comment]
I have added the file in https://github.com/pcurt/MMM-BlaguesAPI/commit/7075e4c0bd39e65711c7d45cb5f3e4246869eb64

**Comment by KristjanESPERANTO** [comment]
Thanks! :+1: :slightly_smiling_face:
